# HISTOGRAM
# Generate a histogram - the distribution of salaries among employees in the dataset.
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
df = pd.read_csv("C:/Users/ayesh/Downloads/Employee data.csv") #print(df)
df.plot(kind="hist")
plt.title('DISTRIBUTION OF SALARIES')
plt.show()  #show the plot
#or
df_can = df.drop(df.columns[[0,2,3,4,6,7,8,9]], axis=1) #Accessing the required columns
df_can.plot(kind="hist")
plt.title("DIstribution of Salaries based on GENDER")
plt.show()


# BAR GRAPH
# Generate a bar plot to compare the average salary of male and female employees
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
df = pd.read_csv("C:/Users/ayesh/Downloads/Employee data.csv") #print(df)
average_salary = df.groupby('gender')['salary'].mean() #calculating average of specific columns using mean()
average_salary.plot(kind="bar", color = ['red','black'])
plt.xlabel("GENDER")
plt.ylabel("SLARY")
plt.title("AVERAGE SALARY OF MALE AND FEMALE")
plt.show()


# SCATTER PLOT
# Create a scatter plot -illustrate the relationship between previous work experience (prevexp) and the current salary of employees.
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
df = pd.read_csv("C:/Users/ayesh/Downloads/Employee data.csv")
df.plot(kind='scatter', x='prevexp', y='salary', figsize=(6, 6), color='red')
plt.title('previous work experience - Salary')
plt.show()


# PIE CHART
# Generate a pie chart to visualize the distribution of educational backgrounds among employees.
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
df = pd.read_csv("C:/Users/ayesh/Downloads/Employee data.csv")
df.groupby('educ')
ed_counts = df['educ'].value_counts()
ed_counts.plot(kind='pie',
                figsize=(5, 6),
                autopct='%1.1f%%', # add in percentages
                startangle=90,         
                pctdistance=10.12,    # the ratio between the center of each pie slice and the start of the text generated by autopct 
            )
plt.title('EDUCATIONAL BACKGROUND')
plt.axis('equal') # Sets the pie chart to look like a circle.
plt.show()

# LINE PLOT
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
df_can = pd.read_excel("D:/DATA_ANALYST_IBM/excel_sheets_data/Canada.xlsx",
                       sheet_name="Canada by Citizenship",
                       skiprows=range(20),
                       skipfooter=2,
                       index_col="OdName"
                       )
df_can = df_can.rename_axis('Country')
df_can = df_can.rename(columns = {'AreaName' : 'Continent', 'RegName' : 'Region'})
df_can = df_can.drop(df_can.columns[[0,1, 2,4,6]], axis=1)
df_can['Total'] = df_can.loc[:, 1980:2013].sum(axis=1)
# #print(df_can.head())
df_can.loc['Haiti',range(1980,2014)].plot(kind='line')
plt.title('Immigration from Haiti')
plt.xlabel('Years')
plt.ylabel('Number of immigrants')
plt.show()